# Generated by Django 2.0.4 on 2018-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_name',
        ),
        migrations.AddField(
            model_name='question',
            name='corrent_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='first_name',
            field=models.CharField(default='rob', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='get_socre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='last_name',
            field=models.CharField(default='rob', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='mouse_click',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='mouse_move',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_name',
            field=models.CharField(default='rob', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_type',
            field=models.CharField(default='rob', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='total_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_socre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
