# Generated by Django 2.0.4 on 2018-04-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20180417_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_number',
            new_name='correct_questions',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='total_number',
            new_name='total_questions',
        ),
    ]
