# Generated by Django 2.0.4 on 2018-04-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20180417_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='get_socre',
            new_name='got_socre',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='mouse_click',
            new_name='mouse_clicks',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='mouse_move',
            new_name='mouse_moves',
        ),
    ]
